### ISSUE TITLE
INVALID_REQUEST - Invalid bot name or alias when using bot routing

### ISSUE THREAD

**Issue by yashpungaliya** [aws-solutions/aws-qnabot#364]
**Describe the bug**
Bot routing does not seem to work with Lex V2 Bots due to `INVALID_REQUEST - Invalid bot name or alias`

**To Reproduce**
* Followed the guide to configure the bot: https://github.com/aws-solutions/aws-qnabot/blob/main/BotRoutingREADME.md
* Region used: eu-west-1
* `aws lex-models get-bots` returns an empty list although bots are present.
* `aws lexv2-runtime recognize-text --bot-id myBotId --bot-alias-id TSTALIASID --locale-id 'en_GB' --session-id 'test_sessio1n' --text 'my input test' gives expected output.

**Expected behavior**
specialtyBotRouter is able to route to the bot defined in the configuration.

**Please complete the following information about the solution:**
- (SO0189) QnABot with admin and client websites - (Master v5.0.0)

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0189) QnABot [...] **v0.0.1**_".

- [ eu-west-1]
- [ No] Was the solution modified from the version published on this repository?
- [ NA] If the answer to the previous question was yes, are the changes available on GitHub?
- [ No] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ Yes] Were there any errors in the CloudWatch Logs?

**Screenshots**
Logs from fulfillment lambda:

~~~


2021-11-30T11:46:24.818Z	9c24fcd5-ea8d-4834-a60d-83e7332e6b57	INFO	Lex parameters: {     "botAlias": "Live_v1",     "botName": "<hidden>",     "inputText": "<hidden>",     "sessionAttributes": {},     "userId": "eu-west-1:fd1e0b3c-4502-449f-bfaa-4d97d065e974" }
--
2021-11-30T11:46:24.853Z	9c24fcd5-ea8d-4834-a60d-83e7332e6b57	INFO	BadRequestException: INVALID_REQUEST - Invalid bot name or alias    at Object.extractError (/opt/nodejs/node_modules/aws-sdk/lib/protocol/json.js:52:27)    at Request.extractError (/opt/nodejs/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)    at Request.callListeners (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:106:20)    at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:78:10)    at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/request.js:688:14)    at Request.transition (/opt/nodejs/node_modules/aws-sdk/lib/request.js:22:10)    at AcceptorStateMachine.runTo (/opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:14:12)    at /opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:26:10    at Request.<anonymous> (/opt/nodejs/node_modules/aws-sdk/lib/request.js:38:9)    at Request.<anonymous> (/opt/nodejs/node_modules/aws-sdk/lib/request.js:690:12)    at Request.callListeners (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:116:18)    at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:78:10)    at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/request.js:688:14)    at Request.transition (/opt/nodejs/node_modules/aws-sdk/lib/request.js:22:10)    at AcceptorStateMachine.runTo (/opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:14:12)    at /opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:26:10    at Request.<anonymous> (/opt/nodejs/node_modules/aws-sdk/lib/request.js:38:9)    at Request.<anonymous> (/opt/nodejs/node_modules/aws-sdk/lib/request.js:690:12)    at Request.callListeners (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:116:18)    at callNextListener (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:96:12)    at IncomingMessage.onEnd (/opt/nodejs/node_modules/aws-sdk/lib/event_listeners.js:336:13)    at IncomingMessage.emit (events.js:326:22) {  code: 'BadRequestException',  time: 2021-11-30T11:46:24.853Z,  requestId: 'a629abbb-99cd-4b72-b7fd-c25c6d62b528',  statusCode: 400,  retryable: false,  retryDelay: 27.877400339023104} BadRequestException: INVALID_REQUEST - Invalid bot name or alias


~~~

**Additional context**

**Comment by bobpskier** [comment]
Next version to be released shortly will contain a fix for this issue and will support bot routing for Lex V2 bots.

**Comment by yashpungaliya** [comment]
Thanks bobpskier@, is there an open request tracking the fix expected date?

**Comment by yashpungaliya** [comment]
Checking if this has been fixed with the latest release

**Comment by yashpungaliya** [comment]
I am assuming this can be closed since latest release says bot routing is supporting on Lex v2 now.
